### ISSUE TITLE
Issue publishing from non-local directory

### ISSUE THREAD

**Issue by BaxW** [quarto-ext/manuscript-template-rstudio#5]
When I clone this repo to a local directory on my computer, I can follow the publishing workflow described [here](https://quarto.org/docs/manuscripts/publishing.html) with no issues. 

However, I do most of my work on a shared network drive. When I clone this to a directory to that drive, I run into issues. When I push to github, the build-deploy action fails with the following error:

```
 Rendering for publish:


[1/2] notebooks/explore-earthquakes.qmd

[2/2] index.qmd
Error in loadNamespace(x) : there is no package called ‘rmarkdown’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
R installation:
  Version: 4.4.1
  Path: /usr/lib/R
  LibPaths:
    - /usr/local/lib/R/site-library
    - /usr/lib/R/site-library
    - /usr/lib/R/library
  knitr: (None)
  rmarkdown: (None)

The knitr package is not available in this R installation.
Install with install.packages("knitr")

The rmarkdown package is not available in this R installation.
Install with install.packages("rmarkdown")

ERROR: Error
    at renderFiles (file:///opt/quarto/bin/quarto.js:85152:29)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async renderProject (file:///opt/quarto/bin/quarto.js:85556:25)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:116854:33)
    at async renderForPublish (file:///opt/quarto/bin/quarto.js:112206:24)
    at async Object.publish1 [as publish] (file:///opt/quarto/bin/quarto.js:112691:26)
    at async publishSite (file:///opt/quarto/bin/quarto.js:116891:38)
    at async publish7 (file:///opt/quarto/bin/quarto.js:117110:61)
    at async doPublish (file:///opt/quarto/bin/quarto.js:117070:13)
    at async publishAction (file:///opt/quarto/bin/quarto.js:117081:9)
Error: Process completed with exit code 1.
```

When I try to run `quarto render` (again, within this shared drive), I get another error:

```
[1/2] notebooks/explore-earthquakes.qmd
ERROR: NotFound: No such file or directory (os error 2): remove '/Volumes/kellrlab/Baxter/GenomicPrediction/web_gp_manuscript/notebooks/explore-earthquakes_files/execute-results'

Stack trace:
    at Object.removeSync (ext:deno_fs/30_fs.js:250:3)
    at removeIfExists (file:///Applications/quarto/bin/quarto.js:4756:14)
    at removeFreezeResults (file:///Applications/quarto/bin/quarto.js:77948:5)
    at renderExecute (file:///Applications/quarto/bin/quarto.js:78007:17)
    at renderFileInternal (file:///Applications/quarto/bin/quarto.js:78201:49)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:78069:17)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:78479:25)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:83077:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8017:13)
```
I'm looking for any insight into fixing these errors. Also, I'm wondering if it is even possible to publish manuscripts that are not saved locally? 

Thanks!!!

**Comment by BaxW** [comment]
Maybe this is related to: https://github.com/quarto-dev/quarto-cli/issues/2380
Which seems to suggest that we shouldn't render qmd in shared drives.

**Comment by BaxW** [comment]
Closing because I've given up on quarto and seems like the devs have too
